[package]
name = "bindings"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
plonky2-cosigning-key-validation = { workspace = true }
libc = "0.2"
anyhow = "1"

[features]
precomputed_verifier_data = []