build:
	cargo build

build-release:
	cargo build --release

test:
	cargo test "testing::tests::test_prove_verify" -- --nocapture

test-release:
	cargo test --release "testing::tests::test_prove_verify" -- --nocapture
