// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: wallet_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_SetupSecurityCardV2_FullMethodName           = "/rpc.WalletService/SetupSecurityCardV2"
	WalletService_SignMessageSecurityCardV2_FullMethodName     = "/rpc.WalletService/SignMessageSecurityCardV2"
	WalletService_PairRequestChallenge_FullMethodName          = "/rpc.WalletService/PairRequestChallenge"
	WalletService_PairSignAndSubmitChallenge_FullMethodName    = "/rpc.WalletService/PairSignAndSubmitChallenge"
	WalletService_StartDiagnosticSession_FullMethodName        = "/rpc.WalletService/StartDiagnosticSession"
	WalletService_PerformDiagnosticScanForUtxos_FullMethodName = "/rpc.WalletService/PerformDiagnosticScanForUtxos"
	WalletService_SubmitDiagnosticLog_FullMethodName           = "/rpc.WalletService/SubmitDiagnosticLog"
	WalletService_PrepareSweepTx_FullMethodName                = "/rpc.WalletService/PrepareSweepTx"
	WalletService_SignAndBroadcastSweepTx_FullMethodName       = "/rpc.WalletService/SignAndBroadcastSweepTx"
	WalletService_StartChallengeSetup_FullMethodName           = "/rpc.WalletService/StartChallengeSetup"
	WalletService_FinishRecoveryCodeSetup_FullMethodName       = "/rpc.WalletService/FinishRecoveryCodeSetup"
	WalletService_PopulateEncryptedMuunKey_FullMethodName      = "/rpc.WalletService/PopulateEncryptedMuunKey"
	WalletService_Save_FullMethodName                          = "/rpc.WalletService/Save"
	WalletService_Get_FullMethodName                           = "/rpc.WalletService/Get"
	WalletService_Delete_FullMethodName                        = "/rpc.WalletService/Delete"
	WalletService_SaveBatch_FullMethodName                     = "/rpc.WalletService/SaveBatch"
	WalletService_GetBatch_FullMethodName                      = "/rpc.WalletService/GetBatch"
	WalletService_GetByPrefix_FullMethodName                   = "/rpc.WalletService/GetByPrefix"
	WalletService_GetSecurityCardsMarketplace_FullMethodName   = "/rpc.WalletService/GetSecurityCardsMarketplace"
	WalletService_GenerateEmergencyKitPDF_FullMethodName       = "/rpc.WalletService/GenerateEmergencyKitPDF"
	WalletService_ResetData_FullMethodName                     = "/rpc.WalletService/ResetData"
	WalletService_ZipDataDir_FullMethodName                    = "/rpc.WalletService/ZipDataDir"
	WalletService_SecureKeyValueStoragePut_FullMethodName      = "/rpc.WalletService/SecureKeyValueStoragePut"
	WalletService_SecureKeyValueStorageGet_FullMethodName      = "/rpc.WalletService/SecureKeyValueStorageGet"
	WalletService_SecureKeyValueStorageDelete_FullMethodName   = "/rpc.WalletService/SecureKeyValueStorageDelete"
	WalletService_SecureKeyValueStorageWipe_FullMethodName     = "/rpc.WalletService/SecureKeyValueStorageWipe"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	// NFC security cards Native->Libwallet API
	SetupSecurityCardV2(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SetupSecurityCardResponse, error)
	SignMessageSecurityCardV2(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PairRequestChallenge(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PairSignAndSubmitChallenge(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PairSignAndSubmitChallengeProgress], error)
	// Diagnostic Mode API
	StartDiagnosticSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DiagnosticSessionDescriptor, error)
	PerformDiagnosticScanForUtxos(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanProgressUpdate], error)
	SubmitDiagnosticLog(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (*DiagnosticSubmitStatus, error)
	PrepareSweepTx(ctx context.Context, in *PrepareSweepTxRequest, opts ...grpc.CallOption) (*PrepareSweepTxResponse, error)
	SignAndBroadcastSweepTx(ctx context.Context, in *SignAndBroadcastSweepTxRequest, opts ...grpc.CallOption) (*SignAndBroadcastSweepTxResponse, error)
	StartChallengeSetup(ctx context.Context, in *ChallengeSetupRequest, opts ...grpc.CallOption) (*SetupChallengeResponse, error)
	FinishRecoveryCodeSetup(ctx context.Context, in *FinishRecoveryCodeSetupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PopulateEncryptedMuunKey(ctx context.Context, in *PopulateEncryptedMuunKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Key-Value Storage
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SaveBatch(ctx context.Context, in *SaveBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error)
	GetByPrefix(ctx context.Context, in *GetByPrefixRequest, opts ...grpc.CallOption) (*GetBatchResponse, error)
	// Marketplace
	GetSecurityCardsMarketplace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSecurityCardsMarketplaceResponse, error)
	// Emergency Kit PDF Generation
	GenerateEmergencyKitPDF(ctx context.Context, in *GenerateEmergencyKitPDFRequest, opts ...grpc.CallOption) (*GenerateEmergencyKitPDFResponse, error)
	// Reset all data from the local SQLite database
	ResetData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Zip all regular files in the libwallet data directory for debug extraction
	ZipDataDir(ctx context.Context, in *ZipDataDirRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Secure Key-Value Storage (native hardware-encrypted storage bridge)
	SecureKeyValueStoragePut(ctx context.Context, in *SecureKeyValueStoragePutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SecureKeyValueStorageGet(ctx context.Context, in *SecureKeyValueStorageGetRequest, opts ...grpc.CallOption) (*SecureKeyValueStorageGetResponse, error)
	SecureKeyValueStorageDelete(ctx context.Context, in *SecureKeyValueStorageDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SecureKeyValueStorageWipe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) SetupSecurityCardV2(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SetupSecurityCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupSecurityCardResponse)
	err := c.cc.Invoke(ctx, WalletService_SetupSecurityCardV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignMessageSecurityCardV2(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_SignMessageSecurityCardV2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PairRequestChallenge(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_PairRequestChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PairSignAndSubmitChallenge(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PairSignAndSubmitChallengeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalletService_ServiceDesc.Streams[0], WalletService_PairSignAndSubmitChallenge_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, PairSignAndSubmitChallengeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_PairSignAndSubmitChallengeClient = grpc.ServerStreamingClient[PairSignAndSubmitChallengeProgress]

func (c *walletServiceClient) StartDiagnosticSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DiagnosticSessionDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticSessionDescriptor)
	err := c.cc.Invoke(ctx, WalletService_StartDiagnosticSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PerformDiagnosticScanForUtxos(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WalletService_ServiceDesc.Streams[1], WalletService_PerformDiagnosticScanForUtxos_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DiagnosticSessionDescriptor, ScanProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_PerformDiagnosticScanForUtxosClient = grpc.ServerStreamingClient[ScanProgressUpdate]

func (c *walletServiceClient) SubmitDiagnosticLog(ctx context.Context, in *DiagnosticSessionDescriptor, opts ...grpc.CallOption) (*DiagnosticSubmitStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticSubmitStatus)
	err := c.cc.Invoke(ctx, WalletService_SubmitDiagnosticLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PrepareSweepTx(ctx context.Context, in *PrepareSweepTxRequest, opts ...grpc.CallOption) (*PrepareSweepTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSweepTxResponse)
	err := c.cc.Invoke(ctx, WalletService_PrepareSweepTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SignAndBroadcastSweepTx(ctx context.Context, in *SignAndBroadcastSweepTxRequest, opts ...grpc.CallOption) (*SignAndBroadcastSweepTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignAndBroadcastSweepTxResponse)
	err := c.cc.Invoke(ctx, WalletService_SignAndBroadcastSweepTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) StartChallengeSetup(ctx context.Context, in *ChallengeSetupRequest, opts ...grpc.CallOption) (*SetupChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetupChallengeResponse)
	err := c.cc.Invoke(ctx, WalletService_StartChallengeSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) FinishRecoveryCodeSetup(ctx context.Context, in *FinishRecoveryCodeSetupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_FinishRecoveryCodeSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) PopulateEncryptedMuunKey(ctx context.Context, in *PopulateEncryptedMuunKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_PopulateEncryptedMuunKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, WalletService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SaveBatch(ctx context.Context, in *SaveBatchRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_SaveBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchResponse)
	err := c.cc.Invoke(ctx, WalletService_GetBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetByPrefix(ctx context.Context, in *GetByPrefixRequest, opts ...grpc.CallOption) (*GetBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBatchResponse)
	err := c.cc.Invoke(ctx, WalletService_GetByPrefix_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetSecurityCardsMarketplace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetSecurityCardsMarketplaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSecurityCardsMarketplaceResponse)
	err := c.cc.Invoke(ctx, WalletService_GetSecurityCardsMarketplace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GenerateEmergencyKitPDF(ctx context.Context, in *GenerateEmergencyKitPDFRequest, opts ...grpc.CallOption) (*GenerateEmergencyKitPDFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateEmergencyKitPDFResponse)
	err := c.cc.Invoke(ctx, WalletService_GenerateEmergencyKitPDF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ResetData(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_ResetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ZipDataDir(ctx context.Context, in *ZipDataDirRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_ZipDataDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SecureKeyValueStoragePut(ctx context.Context, in *SecureKeyValueStoragePutRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_SecureKeyValueStoragePut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SecureKeyValueStorageGet(ctx context.Context, in *SecureKeyValueStorageGetRequest, opts ...grpc.CallOption) (*SecureKeyValueStorageGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecureKeyValueStorageGetResponse)
	err := c.cc.Invoke(ctx, WalletService_SecureKeyValueStorageGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SecureKeyValueStorageDelete(ctx context.Context, in *SecureKeyValueStorageDeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_SecureKeyValueStorageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SecureKeyValueStorageWipe(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_SecureKeyValueStorageWipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	// NFC security cards Native->Libwallet API
	SetupSecurityCardV2(context.Context, *emptypb.Empty) (*SetupSecurityCardResponse, error)
	SignMessageSecurityCardV2(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	PairRequestChallenge(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	PairSignAndSubmitChallenge(*emptypb.Empty, grpc.ServerStreamingServer[PairSignAndSubmitChallengeProgress]) error
	// Diagnostic Mode API
	StartDiagnosticSession(context.Context, *emptypb.Empty) (*DiagnosticSessionDescriptor, error)
	PerformDiagnosticScanForUtxos(*DiagnosticSessionDescriptor, grpc.ServerStreamingServer[ScanProgressUpdate]) error
	SubmitDiagnosticLog(context.Context, *DiagnosticSessionDescriptor) (*DiagnosticSubmitStatus, error)
	PrepareSweepTx(context.Context, *PrepareSweepTxRequest) (*PrepareSweepTxResponse, error)
	SignAndBroadcastSweepTx(context.Context, *SignAndBroadcastSweepTxRequest) (*SignAndBroadcastSweepTxResponse, error)
	StartChallengeSetup(context.Context, *ChallengeSetupRequest) (*SetupChallengeResponse, error)
	FinishRecoveryCodeSetup(context.Context, *FinishRecoveryCodeSetupRequest) (*emptypb.Empty, error)
	PopulateEncryptedMuunKey(context.Context, *PopulateEncryptedMuunKeyRequest) (*emptypb.Empty, error)
	// Key-Value Storage
	Save(context.Context, *SaveRequest) (*emptypb.Empty, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	SaveBatch(context.Context, *SaveBatchRequest) (*emptypb.Empty, error)
	GetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error)
	GetByPrefix(context.Context, *GetByPrefixRequest) (*GetBatchResponse, error)
	// Marketplace
	GetSecurityCardsMarketplace(context.Context, *emptypb.Empty) (*GetSecurityCardsMarketplaceResponse, error)
	// Emergency Kit PDF Generation
	GenerateEmergencyKitPDF(context.Context, *GenerateEmergencyKitPDFRequest) (*GenerateEmergencyKitPDFResponse, error)
	// Reset all data from the local SQLite database
	ResetData(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// Zip all regular files in the libwallet data directory for debug extraction
	ZipDataDir(context.Context, *ZipDataDirRequest) (*emptypb.Empty, error)
	// Secure Key-Value Storage (native hardware-encrypted storage bridge)
	SecureKeyValueStoragePut(context.Context, *SecureKeyValueStoragePutRequest) (*emptypb.Empty, error)
	SecureKeyValueStorageGet(context.Context, *SecureKeyValueStorageGetRequest) (*SecureKeyValueStorageGetResponse, error)
	SecureKeyValueStorageDelete(context.Context, *SecureKeyValueStorageDeleteRequest) (*emptypb.Empty, error)
	SecureKeyValueStorageWipe(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) SetupSecurityCardV2(context.Context, *emptypb.Empty) (*SetupSecurityCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetupSecurityCardV2 not implemented")
}
func (UnimplementedWalletServiceServer) SignMessageSecurityCardV2(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignMessageSecurityCardV2 not implemented")
}
func (UnimplementedWalletServiceServer) PairRequestChallenge(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PairRequestChallenge not implemented")
}
func (UnimplementedWalletServiceServer) PairSignAndSubmitChallenge(*emptypb.Empty, grpc.ServerStreamingServer[PairSignAndSubmitChallengeProgress]) error {
	return status.Errorf(codes.Unimplemented, "method PairSignAndSubmitChallenge not implemented")
}
func (UnimplementedWalletServiceServer) StartDiagnosticSession(context.Context, *emptypb.Empty) (*DiagnosticSessionDescriptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartDiagnosticSession not implemented")
}
func (UnimplementedWalletServiceServer) PerformDiagnosticScanForUtxos(*DiagnosticSessionDescriptor, grpc.ServerStreamingServer[ScanProgressUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method PerformDiagnosticScanForUtxos not implemented")
}
func (UnimplementedWalletServiceServer) SubmitDiagnosticLog(context.Context, *DiagnosticSessionDescriptor) (*DiagnosticSubmitStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDiagnosticLog not implemented")
}
func (UnimplementedWalletServiceServer) PrepareSweepTx(context.Context, *PrepareSweepTxRequest) (*PrepareSweepTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareSweepTx not implemented")
}
func (UnimplementedWalletServiceServer) SignAndBroadcastSweepTx(context.Context, *SignAndBroadcastSweepTxRequest) (*SignAndBroadcastSweepTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignAndBroadcastSweepTx not implemented")
}
func (UnimplementedWalletServiceServer) StartChallengeSetup(context.Context, *ChallengeSetupRequest) (*SetupChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartChallengeSetup not implemented")
}
func (UnimplementedWalletServiceServer) FinishRecoveryCodeSetup(context.Context, *FinishRecoveryCodeSetupRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishRecoveryCodeSetup not implemented")
}
func (UnimplementedWalletServiceServer) PopulateEncryptedMuunKey(context.Context, *PopulateEncryptedMuunKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PopulateEncryptedMuunKey not implemented")
}
func (UnimplementedWalletServiceServer) Save(context.Context, *SaveRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedWalletServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWalletServiceServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWalletServiceServer) SaveBatch(context.Context, *SaveBatchRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveBatch not implemented")
}
func (UnimplementedWalletServiceServer) GetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBatch not implemented")
}
func (UnimplementedWalletServiceServer) GetByPrefix(context.Context, *GetByPrefixRequest) (*GetBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByPrefix not implemented")
}
func (UnimplementedWalletServiceServer) GetSecurityCardsMarketplace(context.Context, *emptypb.Empty) (*GetSecurityCardsMarketplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecurityCardsMarketplace not implemented")
}
func (UnimplementedWalletServiceServer) GenerateEmergencyKitPDF(context.Context, *GenerateEmergencyKitPDFRequest) (*GenerateEmergencyKitPDFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateEmergencyKitPDF not implemented")
}
func (UnimplementedWalletServiceServer) ResetData(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetData not implemented")
}
func (UnimplementedWalletServiceServer) ZipDataDir(context.Context, *ZipDataDirRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZipDataDir not implemented")
}
func (UnimplementedWalletServiceServer) SecureKeyValueStoragePut(context.Context, *SecureKeyValueStoragePutRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecureKeyValueStoragePut not implemented")
}
func (UnimplementedWalletServiceServer) SecureKeyValueStorageGet(context.Context, *SecureKeyValueStorageGetRequest) (*SecureKeyValueStorageGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecureKeyValueStorageGet not implemented")
}
func (UnimplementedWalletServiceServer) SecureKeyValueStorageDelete(context.Context, *SecureKeyValueStorageDeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecureKeyValueStorageDelete not implemented")
}
func (UnimplementedWalletServiceServer) SecureKeyValueStorageWipe(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecureKeyValueStorageWipe not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call pancis, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_SetupSecurityCardV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SetupSecurityCardV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SetupSecurityCardV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SetupSecurityCardV2(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignMessageSecurityCardV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignMessageSecurityCardV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SignMessageSecurityCardV2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignMessageSecurityCardV2(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PairRequestChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PairRequestChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PairRequestChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PairRequestChallenge(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PairSignAndSubmitChallenge_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServiceServer).PairSignAndSubmitChallenge(m, &grpc.GenericServerStream[emptypb.Empty, PairSignAndSubmitChallengeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_PairSignAndSubmitChallengeServer = grpc.ServerStreamingServer[PairSignAndSubmitChallengeProgress]

func _WalletService_StartDiagnosticSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).StartDiagnosticSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_StartDiagnosticSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).StartDiagnosticSession(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PerformDiagnosticScanForUtxos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DiagnosticSessionDescriptor)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WalletServiceServer).PerformDiagnosticScanForUtxos(m, &grpc.GenericServerStream[DiagnosticSessionDescriptor, ScanProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WalletService_PerformDiagnosticScanForUtxosServer = grpc.ServerStreamingServer[ScanProgressUpdate]

func _WalletService_SubmitDiagnosticLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiagnosticSessionDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SubmitDiagnosticLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SubmitDiagnosticLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SubmitDiagnosticLog(ctx, req.(*DiagnosticSessionDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PrepareSweepTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSweepTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PrepareSweepTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PrepareSweepTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PrepareSweepTx(ctx, req.(*PrepareSweepTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SignAndBroadcastSweepTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignAndBroadcastSweepTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SignAndBroadcastSweepTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SignAndBroadcastSweepTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SignAndBroadcastSweepTx(ctx, req.(*SignAndBroadcastSweepTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_StartChallengeSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).StartChallengeSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_StartChallengeSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).StartChallengeSetup(ctx, req.(*ChallengeSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_FinishRecoveryCodeSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishRecoveryCodeSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).FinishRecoveryCodeSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_FinishRecoveryCodeSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).FinishRecoveryCodeSetup(ctx, req.(*FinishRecoveryCodeSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_PopulateEncryptedMuunKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PopulateEncryptedMuunKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).PopulateEncryptedMuunKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_PopulateEncryptedMuunKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).PopulateEncryptedMuunKey(ctx, req.(*PopulateEncryptedMuunKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SaveBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SaveBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SaveBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SaveBatch(ctx, req.(*SaveBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBatch(ctx, req.(*GetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetByPrefix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByPrefixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetByPrefix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetByPrefix_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetByPrefix(ctx, req.(*GetByPrefixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetSecurityCardsMarketplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetSecurityCardsMarketplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetSecurityCardsMarketplace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetSecurityCardsMarketplace(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GenerateEmergencyKitPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateEmergencyKitPDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GenerateEmergencyKitPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GenerateEmergencyKitPDF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GenerateEmergencyKitPDF(ctx, req.(*GenerateEmergencyKitPDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ResetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ResetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ResetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ResetData(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ZipDataDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZipDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ZipDataDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ZipDataDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ZipDataDir(ctx, req.(*ZipDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SecureKeyValueStoragePut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureKeyValueStoragePutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SecureKeyValueStoragePut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SecureKeyValueStoragePut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SecureKeyValueStoragePut(ctx, req.(*SecureKeyValueStoragePutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SecureKeyValueStorageGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureKeyValueStorageGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SecureKeyValueStorageGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SecureKeyValueStorageGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SecureKeyValueStorageGet(ctx, req.(*SecureKeyValueStorageGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SecureKeyValueStorageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecureKeyValueStorageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SecureKeyValueStorageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SecureKeyValueStorageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SecureKeyValueStorageDelete(ctx, req.(*SecureKeyValueStorageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SecureKeyValueStorageWipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SecureKeyValueStorageWipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SecureKeyValueStorageWipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SecureKeyValueStorageWipe(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupSecurityCardV2",
			Handler:    _WalletService_SetupSecurityCardV2_Handler,
		},
		{
			MethodName: "SignMessageSecurityCardV2",
			Handler:    _WalletService_SignMessageSecurityCardV2_Handler,
		},
		{
			MethodName: "PairRequestChallenge",
			Handler:    _WalletService_PairRequestChallenge_Handler,
		},
		{
			MethodName: "StartDiagnosticSession",
			Handler:    _WalletService_StartDiagnosticSession_Handler,
		},
		{
			MethodName: "SubmitDiagnosticLog",
			Handler:    _WalletService_SubmitDiagnosticLog_Handler,
		},
		{
			MethodName: "PrepareSweepTx",
			Handler:    _WalletService_PrepareSweepTx_Handler,
		},
		{
			MethodName: "SignAndBroadcastSweepTx",
			Handler:    _WalletService_SignAndBroadcastSweepTx_Handler,
		},
		{
			MethodName: "StartChallengeSetup",
			Handler:    _WalletService_StartChallengeSetup_Handler,
		},
		{
			MethodName: "FinishRecoveryCodeSetup",
			Handler:    _WalletService_FinishRecoveryCodeSetup_Handler,
		},
		{
			MethodName: "PopulateEncryptedMuunKey",
			Handler:    _WalletService_PopulateEncryptedMuunKey_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _WalletService_Save_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WalletService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _WalletService_Delete_Handler,
		},
		{
			MethodName: "SaveBatch",
			Handler:    _WalletService_SaveBatch_Handler,
		},
		{
			MethodName: "GetBatch",
			Handler:    _WalletService_GetBatch_Handler,
		},
		{
			MethodName: "GetByPrefix",
			Handler:    _WalletService_GetByPrefix_Handler,
		},
		{
			MethodName: "GetSecurityCardsMarketplace",
			Handler:    _WalletService_GetSecurityCardsMarketplace_Handler,
		},
		{
			MethodName: "GenerateEmergencyKitPDF",
			Handler:    _WalletService_GenerateEmergencyKitPDF_Handler,
		},
		{
			MethodName: "ResetData",
			Handler:    _WalletService_ResetData_Handler,
		},
		{
			MethodName: "ZipDataDir",
			Handler:    _WalletService_ZipDataDir_Handler,
		},
		{
			MethodName: "SecureKeyValueStoragePut",
			Handler:    _WalletService_SecureKeyValueStoragePut_Handler,
		},
		{
			MethodName: "SecureKeyValueStorageGet",
			Handler:    _WalletService_SecureKeyValueStorageGet_Handler,
		},
		{
			MethodName: "SecureKeyValueStorageDelete",
			Handler:    _WalletService_SecureKeyValueStorageDelete_Handler,
		},
		{
			MethodName: "SecureKeyValueStorageWipe",
			Handler:    _WalletService_SecureKeyValueStorageWipe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PairSignAndSubmitChallenge",
			Handler:       _WalletService_PairSignAndSubmitChallenge_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PerformDiagnosticScanForUtxos",
			Handler:       _WalletService_PerformDiagnosticScanForUtxos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wallet_service.proto",
}
