// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: wallet_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorType int32

const (
	ErrorType_CLIENT    ErrorType = 0
	ErrorType_LIBWALLET ErrorType = 1
	ErrorType_HOUSTON   ErrorType = 2
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "CLIENT",
		1: "LIBWALLET",
		2: "HOUSTON",
	}
	ErrorType_value = map[string]int32{
		"CLIENT":    0,
		"LIBWALLET": 1,
		"HOUSTON":   2,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_wallet_service_proto_enumTypes[0].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_wallet_service_proto_enumTypes[0]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NullValue int32

const (
	NullValue_NULL_VALUE NullValue = 0
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NULL_VALUE",
	}
	NullValue_value = map[string]int32{
		"NULL_VALUE": 0,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_wallet_service_proto_enumTypes[1].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_wallet_service_proto_enumTypes[1]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ErrorDetail struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type             ErrorType              `protobuf:"varint,1,opt,name=type,proto3,enum=rpc.ErrorType"`
	xxx_hidden_Code             int64                  `protobuf:"varint,2,opt,name=code,proto3"`
	xxx_hidden_Message          string                 `protobuf:"bytes,3,opt,name=message,proto3"`
	xxx_hidden_DeveloperMessage string                 `protobuf:"bytes,4,opt,name=developer_message,json=developerMessage,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_wallet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ErrorDetail) GetType() ErrorType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ErrorType_CLIENT
}

func (x *ErrorDetail) GetCode() int64 {
	if x != nil {
		return x.xxx_hidden_Code
	}
	return 0
}

func (x *ErrorDetail) GetMessage() string {
	if x != nil {
		return x.xxx_hidden_Message
	}
	return ""
}

func (x *ErrorDetail) GetDeveloperMessage() string {
	if x != nil {
		return x.xxx_hidden_DeveloperMessage
	}
	return ""
}

func (x *ErrorDetail) SetType(v ErrorType) {
	x.xxx_hidden_Type = v
}

func (x *ErrorDetail) SetCode(v int64) {
	x.xxx_hidden_Code = v
}

func (x *ErrorDetail) SetMessage(v string) {
	x.xxx_hidden_Message = v
}

func (x *ErrorDetail) SetDeveloperMessage(v string) {
	x.xxx_hidden_DeveloperMessage = v
}

type ErrorDetail_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type             ErrorType
	Code             int64
	Message          string
	DeveloperMessage string
}

func (b0 ErrorDetail_builder) Build() *ErrorDetail {
	m0 := &ErrorDetail{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Code = b.Code
	x.xxx_hidden_Message = b.Message
	x.xxx_hidden_DeveloperMessage = b.DeveloperMessage
	return m0
}

type XpubResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Base58Xpub string                 `protobuf:"bytes,1,opt,name=base58_xpub,json=base58Xpub,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *XpubResponse) Reset() {
	*x = XpubResponse{}
	mi := &file_wallet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XpubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XpubResponse) ProtoMessage() {}

func (x *XpubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *XpubResponse) GetBase58Xpub() string {
	if x != nil {
		return x.xxx_hidden_Base58Xpub
	}
	return ""
}

func (x *XpubResponse) SetBase58Xpub(v string) {
	x.xxx_hidden_Base58Xpub = v
}

type XpubResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Base58Xpub string
}

func (b0 XpubResponse_builder) Build() *XpubResponse {
	m0 := &XpubResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Base58Xpub = b.Base58Xpub
	return m0
}

type SetupSecurityCardResponse struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IsKnownProvider   bool                   `protobuf:"varint,1,opt,name=is_known_provider,json=isKnownProvider,proto3"`
	xxx_hidden_IsCardAlreadyUsed bool                   `protobuf:"varint,2,opt,name=is_card_already_used,json=isCardAlreadyUsed,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SetupSecurityCardResponse) Reset() {
	*x = SetupSecurityCardResponse{}
	mi := &file_wallet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupSecurityCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupSecurityCardResponse) ProtoMessage() {}

func (x *SetupSecurityCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetupSecurityCardResponse) GetIsKnownProvider() bool {
	if x != nil {
		return x.xxx_hidden_IsKnownProvider
	}
	return false
}

func (x *SetupSecurityCardResponse) GetIsCardAlreadyUsed() bool {
	if x != nil {
		return x.xxx_hidden_IsCardAlreadyUsed
	}
	return false
}

func (x *SetupSecurityCardResponse) SetIsKnownProvider(v bool) {
	x.xxx_hidden_IsKnownProvider = v
}

func (x *SetupSecurityCardResponse) SetIsCardAlreadyUsed(v bool) {
	x.xxx_hidden_IsCardAlreadyUsed = v
}

type SetupSecurityCardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IsKnownProvider   bool
	IsCardAlreadyUsed bool
}

func (b0 SetupSecurityCardResponse_builder) Build() *SetupSecurityCardResponse {
	m0 := &SetupSecurityCardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IsKnownProvider = b.IsKnownProvider
	x.xxx_hidden_IsCardAlreadyUsed = b.IsCardAlreadyUsed
	return m0
}

type SignMessageSecurityCardRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MessageHex string                 `protobuf:"bytes,1,opt,name=message_hex,json=messageHex,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SignMessageSecurityCardRequest) Reset() {
	*x = SignMessageSecurityCardRequest{}
	mi := &file_wallet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageSecurityCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageSecurityCardRequest) ProtoMessage() {}

func (x *SignMessageSecurityCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignMessageSecurityCardRequest) GetMessageHex() string {
	if x != nil {
		return x.xxx_hidden_MessageHex
	}
	return ""
}

func (x *SignMessageSecurityCardRequest) SetMessageHex(v string) {
	x.xxx_hidden_MessageHex = v
}

type SignMessageSecurityCardRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MessageHex string
}

func (b0 SignMessageSecurityCardRequest_builder) Build() *SignMessageSecurityCardRequest {
	m0 := &SignMessageSecurityCardRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MessageHex = b.MessageHex
	return m0
}

type SignMessageSecurityCardResponse struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SignedMessageHex string                 `protobuf:"bytes,1,opt,name=signed_message_hex,json=signedMessageHex,proto3"`
	xxx_hidden_IsValidated      bool                   `protobuf:"varint,2,opt,name=is_validated,json=isValidated,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SignMessageSecurityCardResponse) Reset() {
	*x = SignMessageSecurityCardResponse{}
	mi := &file_wallet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignMessageSecurityCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignMessageSecurityCardResponse) ProtoMessage() {}

func (x *SignMessageSecurityCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignMessageSecurityCardResponse) GetSignedMessageHex() string {
	if x != nil {
		return x.xxx_hidden_SignedMessageHex
	}
	return ""
}

func (x *SignMessageSecurityCardResponse) GetIsValidated() bool {
	if x != nil {
		return x.xxx_hidden_IsValidated
	}
	return false
}

func (x *SignMessageSecurityCardResponse) SetSignedMessageHex(v string) {
	x.xxx_hidden_SignedMessageHex = v
}

func (x *SignMessageSecurityCardResponse) SetIsValidated(v bool) {
	x.xxx_hidden_IsValidated = v
}

type SignMessageSecurityCardResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SignedMessageHex string
	IsValidated      bool
}

func (b0 SignMessageSecurityCardResponse_builder) Build() *SignMessageSecurityCardResponse {
	m0 := &SignMessageSecurityCardResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SignedMessageHex = b.SignedMessageHex
	x.xxx_hidden_IsValidated = b.IsValidated
	return m0
}

type DiagnosticSessionDescriptor struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DiagnosticSessionDescriptor) Reset() {
	*x = DiagnosticSessionDescriptor{}
	mi := &file_wallet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticSessionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticSessionDescriptor) ProtoMessage() {}

func (x *DiagnosticSessionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiagnosticSessionDescriptor) GetSessionId() string {
	if x != nil {
		return x.xxx_hidden_SessionId
	}
	return ""
}

func (x *DiagnosticSessionDescriptor) SetSessionId(v string) {
	x.xxx_hidden_SessionId = v
}

type DiagnosticSessionDescriptor_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionId string
}

func (b0 DiagnosticSessionDescriptor_builder) Build() *DiagnosticSessionDescriptor {
	m0 := &DiagnosticSessionDescriptor{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionId = b.SessionId
	return m0
}

type ScanProgressUpdate struct {
	state             protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Update isScanProgressUpdate_Update `protobuf_oneof:"update"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanProgressUpdate) Reset() {
	*x = ScanProgressUpdate{}
	mi := &file_wallet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanProgressUpdate) ProtoMessage() {}

func (x *ScanProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanProgressUpdate) GetFoundUtxoReport() *FoundUtxoReport {
	if x != nil {
		if x, ok := x.xxx_hidden_Update.(*scanProgressUpdate_FoundUtxoReport); ok {
			return x.FoundUtxoReport
		}
	}
	return nil
}

func (x *ScanProgressUpdate) GetScanComplete() *ScanComplete {
	if x != nil {
		if x, ok := x.xxx_hidden_Update.(*scanProgressUpdate_ScanComplete); ok {
			return x.ScanComplete
		}
	}
	return nil
}

func (x *ScanProgressUpdate) SetFoundUtxoReport(v *FoundUtxoReport) {
	if v == nil {
		x.xxx_hidden_Update = nil
		return
	}
	x.xxx_hidden_Update = &scanProgressUpdate_FoundUtxoReport{v}
}

func (x *ScanProgressUpdate) SetScanComplete(v *ScanComplete) {
	if v == nil {
		x.xxx_hidden_Update = nil
		return
	}
	x.xxx_hidden_Update = &scanProgressUpdate_ScanComplete{v}
}

func (x *ScanProgressUpdate) HasUpdate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Update != nil
}

func (x *ScanProgressUpdate) HasFoundUtxoReport() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Update.(*scanProgressUpdate_FoundUtxoReport)
	return ok
}

func (x *ScanProgressUpdate) HasScanComplete() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Update.(*scanProgressUpdate_ScanComplete)
	return ok
}

func (x *ScanProgressUpdate) ClearUpdate() {
	x.xxx_hidden_Update = nil
}

func (x *ScanProgressUpdate) ClearFoundUtxoReport() {
	if _, ok := x.xxx_hidden_Update.(*scanProgressUpdate_FoundUtxoReport); ok {
		x.xxx_hidden_Update = nil
	}
}

func (x *ScanProgressUpdate) ClearScanComplete() {
	if _, ok := x.xxx_hidden_Update.(*scanProgressUpdate_ScanComplete); ok {
		x.xxx_hidden_Update = nil
	}
}

const ScanProgressUpdate_Update_not_set_case case_ScanProgressUpdate_Update = 0
const ScanProgressUpdate_FoundUtxoReport_case case_ScanProgressUpdate_Update = 1
const ScanProgressUpdate_ScanComplete_case case_ScanProgressUpdate_Update = 2

func (x *ScanProgressUpdate) WhichUpdate() case_ScanProgressUpdate_Update {
	if x == nil {
		return ScanProgressUpdate_Update_not_set_case
	}
	switch x.xxx_hidden_Update.(type) {
	case *scanProgressUpdate_FoundUtxoReport:
		return ScanProgressUpdate_FoundUtxoReport_case
	case *scanProgressUpdate_ScanComplete:
		return ScanProgressUpdate_ScanComplete_case
	default:
		return ScanProgressUpdate_Update_not_set_case
	}
}

type ScanProgressUpdate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Update:
	FoundUtxoReport *FoundUtxoReport
	ScanComplete    *ScanComplete
	// -- end of xxx_hidden_Update
}

func (b0 ScanProgressUpdate_builder) Build() *ScanProgressUpdate {
	m0 := &ScanProgressUpdate{}
	b, x := &b0, m0
	_, _ = b, x
	if b.FoundUtxoReport != nil {
		x.xxx_hidden_Update = &scanProgressUpdate_FoundUtxoReport{b.FoundUtxoReport}
	}
	if b.ScanComplete != nil {
		x.xxx_hidden_Update = &scanProgressUpdate_ScanComplete{b.ScanComplete}
	}
	return m0
}

type case_ScanProgressUpdate_Update protoreflect.FieldNumber

func (x case_ScanProgressUpdate_Update) String() string {
	md := file_wallet_service_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isScanProgressUpdate_Update interface {
	isScanProgressUpdate_Update()
}

type scanProgressUpdate_FoundUtxoReport struct {
	FoundUtxoReport *FoundUtxoReport `protobuf:"bytes,1,opt,name=found_utxo_report,json=foundUtxoReport,proto3,oneof"`
}

type scanProgressUpdate_ScanComplete struct {
	ScanComplete *ScanComplete `protobuf:"bytes,2,opt,name=scan_complete,json=scanComplete,proto3,oneof"`
}

func (*scanProgressUpdate_FoundUtxoReport) isScanProgressUpdate_Update() {}

func (*scanProgressUpdate_ScanComplete) isScanProgressUpdate_Update() {}

type FoundUtxoReport struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Address string                 `protobuf:"bytes,1,opt,name=address,proto3"`
	xxx_hidden_Amount  int64                  `protobuf:"varint,2,opt,name=amount,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FoundUtxoReport) Reset() {
	*x = FoundUtxoReport{}
	mi := &file_wallet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundUtxoReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundUtxoReport) ProtoMessage() {}

func (x *FoundUtxoReport) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FoundUtxoReport) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *FoundUtxoReport) GetAmount() int64 {
	if x != nil {
		return x.xxx_hidden_Amount
	}
	return 0
}

func (x *FoundUtxoReport) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

func (x *FoundUtxoReport) SetAmount(v int64) {
	x.xxx_hidden_Amount = v
}

type FoundUtxoReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Address string
	Amount  int64
}

func (b0 FoundUtxoReport_builder) Build() *FoundUtxoReport {
	m0 := &FoundUtxoReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Amount = b.Amount
	return m0
}

type ScanComplete struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status string                 `protobuf:"bytes,1,opt,name=status,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanComplete) Reset() {
	*x = ScanComplete{}
	mi := &file_wallet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanComplete) ProtoMessage() {}

func (x *ScanComplete) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanComplete) GetStatus() string {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return ""
}

func (x *ScanComplete) SetStatus(v string) {
	x.xxx_hidden_Status = v
}

type ScanComplete_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Status string
}

func (b0 ScanComplete_builder) Build() *ScanComplete {
	m0 := &ScanComplete{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Status = b.Status
	return m0
}

type DiagnosticSubmitStatus struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StatusCode    int64                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3"`
	xxx_hidden_StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DiagnosticSubmitStatus) Reset() {
	*x = DiagnosticSubmitStatus{}
	mi := &file_wallet_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticSubmitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticSubmitStatus) ProtoMessage() {}

func (x *DiagnosticSubmitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DiagnosticSubmitStatus) GetStatusCode() int64 {
	if x != nil {
		return x.xxx_hidden_StatusCode
	}
	return 0
}

func (x *DiagnosticSubmitStatus) GetStatusMessage() string {
	if x != nil {
		return x.xxx_hidden_StatusMessage
	}
	return ""
}

func (x *DiagnosticSubmitStatus) SetStatusCode(v int64) {
	x.xxx_hidden_StatusCode = v
}

func (x *DiagnosticSubmitStatus) SetStatusMessage(v string) {
	x.xxx_hidden_StatusMessage = v
}

type DiagnosticSubmitStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StatusCode    int64
	StatusMessage string
}

func (b0 DiagnosticSubmitStatus_builder) Build() *DiagnosticSubmitStatus {
	m0 := &DiagnosticSubmitStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StatusCode = b.StatusCode
	x.xxx_hidden_StatusMessage = b.StatusMessage
	return m0
}

type PrepareSweepTxRequest struct {
	state                            protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_SessionDescriptor     *DiagnosticSessionDescriptor `protobuf:"bytes,1,opt,name=sessionDescriptor,proto3"`
	xxx_hidden_DestinationAddress    string                       `protobuf:"bytes,2,opt,name=destinationAddress,proto3"`
	xxx_hidden_FeeRateInSatsPerVByte float64                      `protobuf:"fixed64,3,opt,name=feeRateInSatsPerVByte,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *PrepareSweepTxRequest) Reset() {
	*x = PrepareSweepTxRequest{}
	mi := &file_wallet_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSweepTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSweepTxRequest) ProtoMessage() {}

func (x *PrepareSweepTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareSweepTxRequest) GetSessionDescriptor() *DiagnosticSessionDescriptor {
	if x != nil {
		return x.xxx_hidden_SessionDescriptor
	}
	return nil
}

func (x *PrepareSweepTxRequest) GetDestinationAddress() string {
	if x != nil {
		return x.xxx_hidden_DestinationAddress
	}
	return ""
}

func (x *PrepareSweepTxRequest) GetFeeRateInSatsPerVByte() float64 {
	if x != nil {
		return x.xxx_hidden_FeeRateInSatsPerVByte
	}
	return 0
}

func (x *PrepareSweepTxRequest) SetSessionDescriptor(v *DiagnosticSessionDescriptor) {
	x.xxx_hidden_SessionDescriptor = v
}

func (x *PrepareSweepTxRequest) SetDestinationAddress(v string) {
	x.xxx_hidden_DestinationAddress = v
}

func (x *PrepareSweepTxRequest) SetFeeRateInSatsPerVByte(v float64) {
	x.xxx_hidden_FeeRateInSatsPerVByte = v
}

func (x *PrepareSweepTxRequest) HasSessionDescriptor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SessionDescriptor != nil
}

func (x *PrepareSweepTxRequest) ClearSessionDescriptor() {
	x.xxx_hidden_SessionDescriptor = nil
}

type PrepareSweepTxRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionDescriptor     *DiagnosticSessionDescriptor
	DestinationAddress    string
	FeeRateInSatsPerVByte float64
}

func (b0 PrepareSweepTxRequest_builder) Build() *PrepareSweepTxRequest {
	m0 := &PrepareSweepTxRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionDescriptor = b.SessionDescriptor
	x.xxx_hidden_DestinationAddress = b.DestinationAddress
	x.xxx_hidden_FeeRateInSatsPerVByte = b.FeeRateInSatsPerVByte
	return m0
}

type PrepareSweepTxResponse struct {
	state                         protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_SessionDescriptor  *DiagnosticSessionDescriptor `protobuf:"bytes,1,opt,name=sessionDescriptor,proto3"`
	xxx_hidden_DestinationAddress string                       `protobuf:"bytes,2,opt,name=destinationAddress,proto3"`
	xxx_hidden_TxSizeInBytes      int64                        `protobuf:"varint,3,opt,name=txSizeInBytes,proto3"`
	xxx_hidden_TxTotalFee         int64                        `protobuf:"varint,4,opt,name=txTotalFee,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PrepareSweepTxResponse) Reset() {
	*x = PrepareSweepTxResponse{}
	mi := &file_wallet_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareSweepTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareSweepTxResponse) ProtoMessage() {}

func (x *PrepareSweepTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PrepareSweepTxResponse) GetSessionDescriptor() *DiagnosticSessionDescriptor {
	if x != nil {
		return x.xxx_hidden_SessionDescriptor
	}
	return nil
}

func (x *PrepareSweepTxResponse) GetDestinationAddress() string {
	if x != nil {
		return x.xxx_hidden_DestinationAddress
	}
	return ""
}

func (x *PrepareSweepTxResponse) GetTxSizeInBytes() int64 {
	if x != nil {
		return x.xxx_hidden_TxSizeInBytes
	}
	return 0
}

func (x *PrepareSweepTxResponse) GetTxTotalFee() int64 {
	if x != nil {
		return x.xxx_hidden_TxTotalFee
	}
	return 0
}

func (x *PrepareSweepTxResponse) SetSessionDescriptor(v *DiagnosticSessionDescriptor) {
	x.xxx_hidden_SessionDescriptor = v
}

func (x *PrepareSweepTxResponse) SetDestinationAddress(v string) {
	x.xxx_hidden_DestinationAddress = v
}

func (x *PrepareSweepTxResponse) SetTxSizeInBytes(v int64) {
	x.xxx_hidden_TxSizeInBytes = v
}

func (x *PrepareSweepTxResponse) SetTxTotalFee(v int64) {
	x.xxx_hidden_TxTotalFee = v
}

func (x *PrepareSweepTxResponse) HasSessionDescriptor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SessionDescriptor != nil
}

func (x *PrepareSweepTxResponse) ClearSessionDescriptor() {
	x.xxx_hidden_SessionDescriptor = nil
}

type PrepareSweepTxResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionDescriptor  *DiagnosticSessionDescriptor
	DestinationAddress string
	TxSizeInBytes      int64
	TxTotalFee         int64
}

func (b0 PrepareSweepTxResponse_builder) Build() *PrepareSweepTxResponse {
	m0 := &PrepareSweepTxResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionDescriptor = b.SessionDescriptor
	x.xxx_hidden_DestinationAddress = b.DestinationAddress
	x.xxx_hidden_TxSizeInBytes = b.TxSizeInBytes
	x.xxx_hidden_TxTotalFee = b.TxTotalFee
	return m0
}

type SignAndBroadcastSweepTxRequest struct {
	state                        protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_SessionDescriptor *DiagnosticSessionDescriptor `protobuf:"bytes,1,opt,name=sessionDescriptor,proto3"`
	xxx_hidden_RecoveryCode      string                       `protobuf:"bytes,2,opt,name=recoveryCode,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SignAndBroadcastSweepTxRequest) Reset() {
	*x = SignAndBroadcastSweepTxRequest{}
	mi := &file_wallet_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignAndBroadcastSweepTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignAndBroadcastSweepTxRequest) ProtoMessage() {}

func (x *SignAndBroadcastSweepTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignAndBroadcastSweepTxRequest) GetSessionDescriptor() *DiagnosticSessionDescriptor {
	if x != nil {
		return x.xxx_hidden_SessionDescriptor
	}
	return nil
}

func (x *SignAndBroadcastSweepTxRequest) GetRecoveryCode() string {
	if x != nil {
		return x.xxx_hidden_RecoveryCode
	}
	return ""
}

func (x *SignAndBroadcastSweepTxRequest) SetSessionDescriptor(v *DiagnosticSessionDescriptor) {
	x.xxx_hidden_SessionDescriptor = v
}

func (x *SignAndBroadcastSweepTxRequest) SetRecoveryCode(v string) {
	x.xxx_hidden_RecoveryCode = v
}

func (x *SignAndBroadcastSweepTxRequest) HasSessionDescriptor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SessionDescriptor != nil
}

func (x *SignAndBroadcastSweepTxRequest) ClearSessionDescriptor() {
	x.xxx_hidden_SessionDescriptor = nil
}

type SignAndBroadcastSweepTxRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionDescriptor *DiagnosticSessionDescriptor
	RecoveryCode      string
}

func (b0 SignAndBroadcastSweepTxRequest_builder) Build() *SignAndBroadcastSweepTxRequest {
	m0 := &SignAndBroadcastSweepTxRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionDescriptor = b.SessionDescriptor
	x.xxx_hidden_RecoveryCode = b.RecoveryCode
	return m0
}

type SignAndBroadcastSweepTxResponse struct {
	state                        protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_SessionDescriptor *DiagnosticSessionDescriptor `protobuf:"bytes,1,opt,name=sessionDescriptor,proto3"`
	xxx_hidden_Txid              string                       `protobuf:"bytes,2,opt,name=txid,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SignAndBroadcastSweepTxResponse) Reset() {
	*x = SignAndBroadcastSweepTxResponse{}
	mi := &file_wallet_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignAndBroadcastSweepTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignAndBroadcastSweepTxResponse) ProtoMessage() {}

func (x *SignAndBroadcastSweepTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignAndBroadcastSweepTxResponse) GetSessionDescriptor() *DiagnosticSessionDescriptor {
	if x != nil {
		return x.xxx_hidden_SessionDescriptor
	}
	return nil
}

func (x *SignAndBroadcastSweepTxResponse) GetTxid() string {
	if x != nil {
		return x.xxx_hidden_Txid
	}
	return ""
}

func (x *SignAndBroadcastSweepTxResponse) SetSessionDescriptor(v *DiagnosticSessionDescriptor) {
	x.xxx_hidden_SessionDescriptor = v
}

func (x *SignAndBroadcastSweepTxResponse) SetTxid(v string) {
	x.xxx_hidden_Txid = v
}

func (x *SignAndBroadcastSweepTxResponse) HasSessionDescriptor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SessionDescriptor != nil
}

func (x *SignAndBroadcastSweepTxResponse) ClearSessionDescriptor() {
	x.xxx_hidden_SessionDescriptor = nil
}

type SignAndBroadcastSweepTxResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SessionDescriptor *DiagnosticSessionDescriptor
	Txid              string
}

func (b0 SignAndBroadcastSweepTxResponse_builder) Build() *SignAndBroadcastSweepTxResponse {
	m0 := &SignAndBroadcastSweepTxResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SessionDescriptor = b.SessionDescriptor
	x.xxx_hidden_Txid = b.Txid
	return m0
}

type ChallengeSetupRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type                string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_PublicKey           string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3"`
	xxx_hidden_Salt                string                 `protobuf:"bytes,3,opt,name=salt,proto3"`
	xxx_hidden_EncryptedPrivateKey string                 `protobuf:"bytes,4,opt,name=encrypted_private_key,json=encryptedPrivateKey,proto3"`
	xxx_hidden_Version             int32                  `protobuf:"varint,5,opt,name=version,proto3"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ChallengeSetupRequest) Reset() {
	*x = ChallengeSetupRequest{}
	mi := &file_wallet_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChallengeSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChallengeSetupRequest) ProtoMessage() {}

func (x *ChallengeSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ChallengeSetupRequest) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *ChallengeSetupRequest) GetPublicKey() string {
	if x != nil {
		return x.xxx_hidden_PublicKey
	}
	return ""
}

func (x *ChallengeSetupRequest) GetSalt() string {
	if x != nil {
		return x.xxx_hidden_Salt
	}
	return ""
}

func (x *ChallengeSetupRequest) GetEncryptedPrivateKey() string {
	if x != nil {
		return x.xxx_hidden_EncryptedPrivateKey
	}
	return ""
}

func (x *ChallengeSetupRequest) GetVersion() int32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *ChallengeSetupRequest) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *ChallengeSetupRequest) SetPublicKey(v string) {
	x.xxx_hidden_PublicKey = v
}

func (x *ChallengeSetupRequest) SetSalt(v string) {
	x.xxx_hidden_Salt = v
}

func (x *ChallengeSetupRequest) SetEncryptedPrivateKey(v string) {
	x.xxx_hidden_EncryptedPrivateKey = v
}

func (x *ChallengeSetupRequest) SetVersion(v int32) {
	x.xxx_hidden_Version = v
}

type ChallengeSetupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type                string
	PublicKey           string
	Salt                string
	EncryptedPrivateKey string
	Version             int32
}

func (b0 ChallengeSetupRequest_builder) Build() *ChallengeSetupRequest {
	m0 := &ChallengeSetupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_PublicKey = b.PublicKey
	x.xxx_hidden_Salt = b.Salt
	x.xxx_hidden_EncryptedPrivateKey = b.EncryptedPrivateKey
	x.xxx_hidden_Version = b.Version
	return m0
}

type SetupChallengeResponse struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MuunKey            *string                `protobuf:"bytes,1,opt,name=muun_key,json=muunKey,proto3,oneof"`
	xxx_hidden_MuunKeyFingerprint *string                `protobuf:"bytes,2,opt,name=muun_key_fingerprint,json=muunKeyFingerprint,proto3,oneof"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SetupChallengeResponse) Reset() {
	*x = SetupChallengeResponse{}
	mi := &file_wallet_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupChallengeResponse) ProtoMessage() {}

func (x *SetupChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetupChallengeResponse) GetMuunKey() string {
	if x != nil {
		if x.xxx_hidden_MuunKey != nil {
			return *x.xxx_hidden_MuunKey
		}
		return ""
	}
	return ""
}

func (x *SetupChallengeResponse) GetMuunKeyFingerprint() string {
	if x != nil {
		if x.xxx_hidden_MuunKeyFingerprint != nil {
			return *x.xxx_hidden_MuunKeyFingerprint
		}
		return ""
	}
	return ""
}

func (x *SetupChallengeResponse) SetMuunKey(v string) {
	x.xxx_hidden_MuunKey = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *SetupChallengeResponse) SetMuunKeyFingerprint(v string) {
	x.xxx_hidden_MuunKeyFingerprint = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *SetupChallengeResponse) HasMuunKey() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetupChallengeResponse) HasMuunKeyFingerprint() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SetupChallengeResponse) ClearMuunKey() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MuunKey = nil
}

func (x *SetupChallengeResponse) ClearMuunKeyFingerprint() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_MuunKeyFingerprint = nil
}

type SetupChallengeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MuunKey            *string
	MuunKeyFingerprint *string
}

func (b0 SetupChallengeResponse_builder) Build() *SetupChallengeResponse {
	m0 := &SetupChallengeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MuunKey != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_MuunKey = b.MuunKey
	}
	if b.MuunKeyFingerprint != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_MuunKeyFingerprint = b.MuunKeyFingerprint
	}
	return m0
}

type FinishRecoveryCodeSetupRequest struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecoveryCodePublicKeyHex string                 `protobuf:"bytes,1,opt,name=recovery_code_public_key_hex,json=recoveryCodePublicKeyHex,proto3"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *FinishRecoveryCodeSetupRequest) Reset() {
	*x = FinishRecoveryCodeSetupRequest{}
	mi := &file_wallet_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRecoveryCodeSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRecoveryCodeSetupRequest) ProtoMessage() {}

func (x *FinishRecoveryCodeSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FinishRecoveryCodeSetupRequest) GetRecoveryCodePublicKeyHex() string {
	if x != nil {
		return x.xxx_hidden_RecoveryCodePublicKeyHex
	}
	return ""
}

func (x *FinishRecoveryCodeSetupRequest) SetRecoveryCodePublicKeyHex(v string) {
	x.xxx_hidden_RecoveryCodePublicKeyHex = v
}

type FinishRecoveryCodeSetupRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecoveryCodePublicKeyHex string
}

func (b0 FinishRecoveryCodeSetupRequest_builder) Build() *FinishRecoveryCodeSetupRequest {
	m0 := &FinishRecoveryCodeSetupRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RecoveryCodePublicKeyHex = b.RecoveryCodePublicKeyHex
	return m0
}

type PopulateEncryptedMuunKeyRequest struct {
	state                               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecoveryCodePublicKeyHex string                 `protobuf:"bytes,1,opt,name=recovery_code_public_key_hex,json=recoveryCodePublicKeyHex,proto3"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *PopulateEncryptedMuunKeyRequest) Reset() {
	*x = PopulateEncryptedMuunKeyRequest{}
	mi := &file_wallet_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulateEncryptedMuunKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulateEncryptedMuunKeyRequest) ProtoMessage() {}

func (x *PopulateEncryptedMuunKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PopulateEncryptedMuunKeyRequest) GetRecoveryCodePublicKeyHex() string {
	if x != nil {
		return x.xxx_hidden_RecoveryCodePublicKeyHex
	}
	return ""
}

func (x *PopulateEncryptedMuunKeyRequest) SetRecoveryCodePublicKeyHex(v string) {
	x.xxx_hidden_RecoveryCodePublicKeyHex = v
}

type PopulateEncryptedMuunKeyRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecoveryCodePublicKeyHex string
}

func (b0 PopulateEncryptedMuunKeyRequest_builder) Build() *PopulateEncryptedMuunKeyRequest {
	m0 := &PopulateEncryptedMuunKeyRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_RecoveryCodePublicKeyHex = b.RecoveryCodePublicKeyHex
	return m0
}

type Struct struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Fields map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_wallet_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Struct) GetFields() map[string]*Value {
	if x != nil {
		return x.xxx_hidden_Fields
	}
	return nil
}

func (x *Struct) SetFields(v map[string]*Value) {
	x.xxx_hidden_Fields = v
}

type Struct_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Unordered map of dynamically typed values
	Fields map[string]*Value
}

func (b0 Struct_builder) Build() *Struct {
	m0 := &Struct{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Fields = b.Fields
	return m0
}

type Value struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Kind isValue_Kind           `protobuf_oneof:"kind"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_wallet_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Value) GetNullValue() NullValue {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_NullValue); ok {
			return x.NullValue
		}
	}
	return NullValue_NULL_VALUE
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetLongValue() int64 {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_LongValue); ok {
			return x.LongValue
		}
	}
	return 0
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.xxx_hidden_Kind.(*value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) SetNullValue(v NullValue) {
	x.xxx_hidden_Kind = &value_NullValue{v}
}

func (x *Value) SetDoubleValue(v float64) {
	x.xxx_hidden_Kind = &value_DoubleValue{v}
}

func (x *Value) SetIntValue(v int32) {
	x.xxx_hidden_Kind = &value_IntValue{v}
}

func (x *Value) SetLongValue(v int64) {
	x.xxx_hidden_Kind = &value_LongValue{v}
}

func (x *Value) SetStringValue(v string) {
	x.xxx_hidden_Kind = &value_StringValue{v}
}

func (x *Value) SetBoolValue(v bool) {
	x.xxx_hidden_Kind = &value_BoolValue{v}
}

func (x *Value) HasKind() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kind != nil
}

func (x *Value) HasNullValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_NullValue)
	return ok
}

func (x *Value) HasDoubleValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_DoubleValue)
	return ok
}

func (x *Value) HasIntValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_IntValue)
	return ok
}

func (x *Value) HasLongValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_LongValue)
	return ok
}

func (x *Value) HasStringValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_StringValue)
	return ok
}

func (x *Value) HasBoolValue() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Kind.(*value_BoolValue)
	return ok
}

func (x *Value) ClearKind() {
	x.xxx_hidden_Kind = nil
}

func (x *Value) ClearNullValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_NullValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearDoubleValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_DoubleValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearIntValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_IntValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearLongValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_LongValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearStringValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_StringValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

func (x *Value) ClearBoolValue() {
	if _, ok := x.xxx_hidden_Kind.(*value_BoolValue); ok {
		x.xxx_hidden_Kind = nil
	}
}

const Value_Kind_not_set_case case_Value_Kind = 0
const Value_NullValue_case case_Value_Kind = 1
const Value_DoubleValue_case case_Value_Kind = 2
const Value_IntValue_case case_Value_Kind = 3
const Value_LongValue_case case_Value_Kind = 4
const Value_StringValue_case case_Value_Kind = 5
const Value_BoolValue_case case_Value_Kind = 6

func (x *Value) WhichKind() case_Value_Kind {
	if x == nil {
		return Value_Kind_not_set_case
	}
	switch x.xxx_hidden_Kind.(type) {
	case *value_NullValue:
		return Value_NullValue_case
	case *value_DoubleValue:
		return Value_DoubleValue_case
	case *value_IntValue:
		return Value_IntValue_case
	case *value_LongValue:
		return Value_LongValue_case
	case *value_StringValue:
		return Value_StringValue_case
	case *value_BoolValue:
		return Value_BoolValue_case
	default:
		return Value_Kind_not_set_case
	}
}

type Value_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Kind:
	NullValue   *NullValue
	DoubleValue *float64
	IntValue    *int32
	LongValue   *int64
	StringValue *string
	BoolValue   *bool
	// -- end of xxx_hidden_Kind
}

func (b0 Value_builder) Build() *Value {
	m0 := &Value{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NullValue != nil {
		x.xxx_hidden_Kind = &value_NullValue{*b.NullValue}
	}
	if b.DoubleValue != nil {
		x.xxx_hidden_Kind = &value_DoubleValue{*b.DoubleValue}
	}
	if b.IntValue != nil {
		x.xxx_hidden_Kind = &value_IntValue{*b.IntValue}
	}
	if b.LongValue != nil {
		x.xxx_hidden_Kind = &value_LongValue{*b.LongValue}
	}
	if b.StringValue != nil {
		x.xxx_hidden_Kind = &value_StringValue{*b.StringValue}
	}
	if b.BoolValue != nil {
		x.xxx_hidden_Kind = &value_BoolValue{*b.BoolValue}
	}
	return m0
}

type case_Value_Kind protoreflect.FieldNumber

func (x case_Value_Kind) String() string {
	md := file_wallet_service_proto_msgTypes[19].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isValue_Kind interface {
	isValue_Kind()
}

type value_NullValue struct {
	NullValue NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=rpc.NullValue,oneof"`
}

type value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type value_IntValue struct {
	IntValue int32 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type value_LongValue struct {
	LongValue int64 `protobuf:"varint,4,opt,name=long_value,json=longValue,proto3,oneof"`
}

type value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type value_BoolValue struct {
	BoolValue bool `protobuf:"varint,6,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*value_NullValue) isValue_Kind() {}

func (*value_DoubleValue) isValue_Kind() {}

func (*value_IntValue) isValue_Kind() {}

func (*value_LongValue) isValue_Kind() {}

func (*value_StringValue) isValue_Kind() {}

func (*value_BoolValue) isValue_Kind() {}

type SaveRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_wallet_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *SaveRequest) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *SaveRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *SaveRequest) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *SaveRequest) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *SaveRequest) ClearValue() {
	x.xxx_hidden_Value = nil
}

type SaveRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value *Value
}

func (b0 SaveRequest_builder) Build() *SaveRequest {
	m0 := &SaveRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type GetRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_wallet_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *GetRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

type GetRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key string
}

func (b0 GetRequest_builder) Build() *GetRequest {
	m0 := &GetRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

type GetResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value *Value                 `protobuf:"bytes,1,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_wallet_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetResponse) GetValue() *Value {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetResponse) SetValue(v *Value) {
	x.xxx_hidden_Value = v
}

func (x *GetResponse) HasValue() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Value != nil
}

func (x *GetResponse) ClearValue() {
	x.xxx_hidden_Value = nil
}

type GetResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value *Value
}

func (b0 GetResponse_builder) Build() *GetResponse {
	m0 := &GetResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type DeleteRequest struct {
	state          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_wallet_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *DeleteRequest) SetKey(v string) {
	x.xxx_hidden_Key = v
}

type DeleteRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key string
}

func (b0 DeleteRequest_builder) Build() *DeleteRequest {
	m0 := &DeleteRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	return m0
}

type SaveBatchRequest struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *Struct                `protobuf:"bytes,1,opt,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SaveBatchRequest) Reset() {
	*x = SaveBatchRequest{}
	mi := &file_wallet_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveBatchRequest) ProtoMessage() {}

func (x *SaveBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SaveBatchRequest) GetItems() *Struct {
	if x != nil {
		return x.xxx_hidden_Items
	}
	return nil
}

func (x *SaveBatchRequest) SetItems(v *Struct) {
	x.xxx_hidden_Items = v
}

func (x *SaveBatchRequest) HasItems() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Items != nil
}

func (x *SaveBatchRequest) ClearItems() {
	x.xxx_hidden_Items = nil
}

type SaveBatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items *Struct
}

func (b0 SaveBatchRequest_builder) Build() *SaveBatchRequest {
	m0 := &SaveBatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = b.Items
	return m0
}

type GetBatchRequest struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Keys []string               `protobuf:"bytes,1,rep,name=keys,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBatchRequest) Reset() {
	*x = GetBatchRequest{}
	mi := &file_wallet_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchRequest) ProtoMessage() {}

func (x *GetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBatchRequest) GetKeys() []string {
	if x != nil {
		return x.xxx_hidden_Keys
	}
	return nil
}

func (x *GetBatchRequest) SetKeys(v []string) {
	x.xxx_hidden_Keys = v
}

type GetBatchRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Keys []string
}

func (b0 GetBatchRequest_builder) Build() *GetBatchRequest {
	m0 := &GetBatchRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Keys = b.Keys
	return m0
}

type GetBatchResponse struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Items *Struct                `protobuf:"bytes,1,opt,name=items,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBatchResponse) Reset() {
	*x = GetBatchResponse{}
	mi := &file_wallet_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchResponse) ProtoMessage() {}

func (x *GetBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetBatchResponse) GetItems() *Struct {
	if x != nil {
		return x.xxx_hidden_Items
	}
	return nil
}

func (x *GetBatchResponse) SetItems(v *Struct) {
	x.xxx_hidden_Items = v
}

func (x *GetBatchResponse) HasItems() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Items != nil
}

func (x *GetBatchResponse) ClearItems() {
	x.xxx_hidden_Items = nil
}

type GetBatchResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Items *Struct
}

func (b0 GetBatchResponse_builder) Build() *GetBatchResponse {
	m0 := &GetBatchResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Items = b.Items
	return m0
}

type GetByPrefixRequest struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Prefix string                 `protobuf:"bytes,1,opt,name=prefix,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetByPrefixRequest) Reset() {
	*x = GetByPrefixRequest{}
	mi := &file_wallet_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByPrefixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByPrefixRequest) ProtoMessage() {}

func (x *GetByPrefixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetByPrefixRequest) GetPrefix() string {
	if x != nil {
		return x.xxx_hidden_Prefix
	}
	return ""
}

func (x *GetByPrefixRequest) SetPrefix(v string) {
	x.xxx_hidden_Prefix = v
}

type GetByPrefixRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Prefix string
}

func (b0 GetByPrefixRequest_builder) Build() *GetByPrefixRequest {
	m0 := &GetByPrefixRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Prefix = b.Prefix
	return m0
}

var File_wallet_service_proto protoreflect.FileDescriptor

var file_wallet_service_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x0b, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x0c, 0x58, 0x70, 0x75, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x73, 0x65, 0x35,
	0x38, 0x5f, 0x78, 0x70, 0x75, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x35, 0x38, 0x58, 0x70, 0x75, 0x62, 0x22, 0x78, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x75,
	0x70, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x69, 0x73, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x12, 0x2f, 0x0a, 0x14, 0x69, 0x73, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x6c, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x69, 0x73, 0x43, 0x61, 0x72, 0x64, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x55, 0x73,
	0x65, 0x64, 0x22, 0x41, 0x0a, 0x1e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x68, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x48, 0x65, 0x78, 0x22, 0x72, 0x0a, 0x1f, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x68, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x48, 0x65, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73,
	0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x3c, 0x0a, 0x1b, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x9c, 0x01, 0x0a, 0x12, 0x53, 0x63, 0x61, 0x6e,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x42,
	0x0a, 0x11, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x74, 0x78, 0x6f, 0x5f, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x46, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48,
	0x00, 0x52, 0x0f, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x55, 0x74, 0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x38, 0x0a, 0x0d, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c,
	0x73, 0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x08, 0x0a, 0x06,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x43, 0x0a, 0x0f, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x55,
	0x74, 0x78, 0x6f, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x53,
	0x63, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x60, 0x0a, 0x16, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xcd, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x53, 0x77, 0x65, 0x65, 0x70, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x4e, 0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x11, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12,
	0x2e, 0x0a, 0x12, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x64, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x34, 0x0a, 0x15, 0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x53, 0x61, 0x74, 0x73,
	0x50, 0x65, 0x72, 0x56, 0x42, 0x79, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x15,
	0x66, 0x65, 0x65, 0x52, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x53, 0x61, 0x74, 0x73, 0x50, 0x65, 0x72,
	0x56, 0x42, 0x79, 0x74, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72,
	0x65, 0x53, 0x77, 0x65, 0x65, 0x70, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4e, 0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x11, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x12, 0x2e, 0x0a, 0x12, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x24, 0x0a, 0x0d, 0x74, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x74, 0x78, 0x53, 0x69, 0x7a, 0x65, 0x49,
	0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x78, 0x54, 0x6f, 0x74, 0x61,
	0x6c, 0x46, 0x65, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x78, 0x54, 0x6f,
	0x74, 0x61, 0x6c, 0x46, 0x65, 0x65, 0x22, 0x94, 0x01, 0x0a, 0x1e, 0x53, 0x69, 0x67, 0x6e, 0x41,
	0x6e, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x77, 0x65, 0x65, 0x70,
	0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4e, 0x0a, 0x11, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e,
	0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x85, 0x01,
	0x0a, 0x1f, 0x53, 0x69, 0x67, 0x6e, 0x41, 0x6e, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x53, 0x77, 0x65, 0x65, 0x70, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4e, 0x0a, 0x11, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52, 0x11,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x78, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x78, 0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x15, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x95, 0x01, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x08, 0x6d, 0x75, 0x75, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x75, 0x75, 0x6e, 0x4b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12,
	0x35, 0x0a, 0x14, 0x6d, 0x75, 0x75, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6e, 0x67,
	0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x12, 0x6d, 0x75, 0x75, 0x6e, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6d, 0x75, 0x75, 0x6e, 0x5f,
	0x6b, 0x65, 0x79, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x6d, 0x75, 0x75, 0x6e, 0x5f, 0x6b, 0x65, 0x79,
	0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x1e,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e,
	0x0a, 0x1c, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x48, 0x65, 0x78, 0x22, 0x61,
	0x0a, 0x1f, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x4d, 0x75, 0x75, 0x6e, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3e, 0x0a, 0x1c, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x68, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x18, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x48, 0x65,
	0x78, 0x22, 0x80, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x2f, 0x0a, 0x06,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x45, 0x0a,
	0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xeb, 0x01, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2f,
	0x0a, 0x0a, 0x6e, 0x75, 0x6c, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x48, 0x00, 0x52, 0x09, 0x6e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x23, 0x0a, 0x0c, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x62, 0x6f, 0x6f,
	0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52,
	0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x22, 0x41, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x10, 0x53, 0x61, 0x76,
	0x65, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x35, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x2c,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x2a, 0x33, 0x0a, 0x09,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x49,
	0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x49, 0x42, 0x57, 0x41, 0x4c, 0x4c,
	0x45, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x4f, 0x55, 0x53, 0x54, 0x4f, 0x4e, 0x10,
	0x02, 0x2a, 0x1b, 0x0a, 0x09, 0x4e, 0x75, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e,
	0x0a, 0x0a, 0x4e, 0x55, 0x4c, 0x4c, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x10, 0x00, 0x32, 0x97,
	0x0b, 0x0a, 0x0d, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3e, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x58, 0x70, 0x75, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x43, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x64, 0x0a, 0x17, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x13, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61, 0x72, 0x64,
	0x56, 0x32, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x19, 0x53, 0x69,
	0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x43, 0x61, 0x72, 0x64, 0x56, 0x32, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x52, 0x0a, 0x16, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x5c, 0x0a, 0x1d, 0x50,
	0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63,
	0x53, 0x63, 0x61, 0x6e, 0x46, 0x6f, 0x72, 0x55, 0x74, 0x78, 0x6f, 0x73, 0x12, 0x20, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x1a, 0x17,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x54, 0x0a, 0x13, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x4c, 0x6f, 0x67,
	0x12, 0x20, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x6f, 0x72, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x49, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53, 0x77, 0x65, 0x65, 0x70, 0x54,
	0x78, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53,
	0x77, 0x65, 0x65, 0x70, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65, 0x53, 0x77, 0x65, 0x65, 0x70,
	0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x17, 0x53, 0x69,
	0x67, 0x6e, 0x41, 0x6e, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x77,
	0x65, 0x65, 0x70, 0x54, 0x78, 0x12, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x41, 0x6e, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x53, 0x77, 0x65, 0x65,
	0x70, 0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x41, 0x6e, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x53, 0x77, 0x65, 0x65, 0x70, 0x54, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4e, 0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e,
	0x67, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x75, 0x70, 0x43,
	0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x56, 0x0a, 0x17, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x23, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x58, 0x0a, 0x18, 0x50, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d, 0x75, 0x75,
	0x6e, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d, 0x75, 0x75, 0x6e,
	0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x12, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x37, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x42, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x75, 0x6e, 0x2f, 0x6c, 0x69, 0x62, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var file_wallet_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_wallet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_wallet_service_proto_goTypes = []any{
	(ErrorType)(0),                          // 0: rpc.ErrorType
	(NullValue)(0),                          // 1: rpc.NullValue
	(*ErrorDetail)(nil),                     // 2: rpc.ErrorDetail
	(*XpubResponse)(nil),                    // 3: rpc.XpubResponse
	(*SetupSecurityCardResponse)(nil),       // 4: rpc.SetupSecurityCardResponse
	(*SignMessageSecurityCardRequest)(nil),  // 5: rpc.SignMessageSecurityCardRequest
	(*SignMessageSecurityCardResponse)(nil), // 6: rpc.SignMessageSecurityCardResponse
	(*DiagnosticSessionDescriptor)(nil),     // 7: rpc.DiagnosticSessionDescriptor
	(*ScanProgressUpdate)(nil),              // 8: rpc.ScanProgressUpdate
	(*FoundUtxoReport)(nil),                 // 9: rpc.FoundUtxoReport
	(*ScanComplete)(nil),                    // 10: rpc.ScanComplete
	(*DiagnosticSubmitStatus)(nil),          // 11: rpc.DiagnosticSubmitStatus
	(*PrepareSweepTxRequest)(nil),           // 12: rpc.PrepareSweepTxRequest
	(*PrepareSweepTxResponse)(nil),          // 13: rpc.PrepareSweepTxResponse
	(*SignAndBroadcastSweepTxRequest)(nil),  // 14: rpc.SignAndBroadcastSweepTxRequest
	(*SignAndBroadcastSweepTxResponse)(nil), // 15: rpc.SignAndBroadcastSweepTxResponse
	(*ChallengeSetupRequest)(nil),           // 16: rpc.ChallengeSetupRequest
	(*SetupChallengeResponse)(nil),          // 17: rpc.SetupChallengeResponse
	(*FinishRecoveryCodeSetupRequest)(nil),  // 18: rpc.FinishRecoveryCodeSetupRequest
	(*PopulateEncryptedMuunKeyRequest)(nil), // 19: rpc.PopulateEncryptedMuunKeyRequest
	(*Struct)(nil),                          // 20: rpc.Struct
	(*Value)(nil),                           // 21: rpc.Value
	(*SaveRequest)(nil),                     // 22: rpc.SaveRequest
	(*GetRequest)(nil),                      // 23: rpc.GetRequest
	(*GetResponse)(nil),                     // 24: rpc.GetResponse
	(*DeleteRequest)(nil),                   // 25: rpc.DeleteRequest
	(*SaveBatchRequest)(nil),                // 26: rpc.SaveBatchRequest
	(*GetBatchRequest)(nil),                 // 27: rpc.GetBatchRequest
	(*GetBatchResponse)(nil),                // 28: rpc.GetBatchResponse
	(*GetByPrefixRequest)(nil),              // 29: rpc.GetByPrefixRequest
	nil,                                     // 30: rpc.Struct.FieldsEntry
	(*emptypb.Empty)(nil),                   // 31: google.protobuf.Empty
}
var file_wallet_service_proto_depIdxs = []int32{
	0,  // 0: rpc.ErrorDetail.type:type_name -> rpc.ErrorType
	9,  // 1: rpc.ScanProgressUpdate.found_utxo_report:type_name -> rpc.FoundUtxoReport
	10, // 2: rpc.ScanProgressUpdate.scan_complete:type_name -> rpc.ScanComplete
	7,  // 3: rpc.PrepareSweepTxRequest.sessionDescriptor:type_name -> rpc.DiagnosticSessionDescriptor
	7,  // 4: rpc.PrepareSweepTxResponse.sessionDescriptor:type_name -> rpc.DiagnosticSessionDescriptor
	7,  // 5: rpc.SignAndBroadcastSweepTxRequest.sessionDescriptor:type_name -> rpc.DiagnosticSessionDescriptor
	7,  // 6: rpc.SignAndBroadcastSweepTxResponse.sessionDescriptor:type_name -> rpc.DiagnosticSessionDescriptor
	30, // 7: rpc.Struct.fields:type_name -> rpc.Struct.FieldsEntry
	1,  // 8: rpc.Value.null_value:type_name -> rpc.NullValue
	21, // 9: rpc.SaveRequest.value:type_name -> rpc.Value
	21, // 10: rpc.GetResponse.value:type_name -> rpc.Value
	20, // 11: rpc.SaveBatchRequest.items:type_name -> rpc.Struct
	20, // 12: rpc.GetBatchResponse.items:type_name -> rpc.Struct
	21, // 13: rpc.Struct.FieldsEntry.value:type_name -> rpc.Value
	31, // 14: rpc.WalletService.SetupSecurityCard:input_type -> google.protobuf.Empty
	31, // 15: rpc.WalletService.ResetSecurityCard:input_type -> google.protobuf.Empty
	5,  // 16: rpc.WalletService.SignMessageSecurityCard:input_type -> rpc.SignMessageSecurityCardRequest
	31, // 17: rpc.WalletService.SetupSecurityCardV2:input_type -> google.protobuf.Empty
	31, // 18: rpc.WalletService.SignMessageSecurityCardV2:input_type -> google.protobuf.Empty
	31, // 19: rpc.WalletService.StartDiagnosticSession:input_type -> google.protobuf.Empty
	7,  // 20: rpc.WalletService.PerformDiagnosticScanForUtxos:input_type -> rpc.DiagnosticSessionDescriptor
	7,  // 21: rpc.WalletService.SubmitDiagnosticLog:input_type -> rpc.DiagnosticSessionDescriptor
	12, // 22: rpc.WalletService.PrepareSweepTx:input_type -> rpc.PrepareSweepTxRequest
	14, // 23: rpc.WalletService.SignAndBroadcastSweepTx:input_type -> rpc.SignAndBroadcastSweepTxRequest
	16, // 24: rpc.WalletService.StartChallengeSetup:input_type -> rpc.ChallengeSetupRequest
	18, // 25: rpc.WalletService.FinishRecoveryCodeSetup:input_type -> rpc.FinishRecoveryCodeSetupRequest
	19, // 26: rpc.WalletService.PopulateEncryptedMuunKey:input_type -> rpc.PopulateEncryptedMuunKeyRequest
	22, // 27: rpc.WalletService.Save:input_type -> rpc.SaveRequest
	23, // 28: rpc.WalletService.Get:input_type -> rpc.GetRequest
	25, // 29: rpc.WalletService.Delete:input_type -> rpc.DeleteRequest
	26, // 30: rpc.WalletService.SaveBatch:input_type -> rpc.SaveBatchRequest
	27, // 31: rpc.WalletService.GetBatch:input_type -> rpc.GetBatchRequest
	29, // 32: rpc.WalletService.GetByPrefix:input_type -> rpc.GetByPrefixRequest
	3,  // 33: rpc.WalletService.SetupSecurityCard:output_type -> rpc.XpubResponse
	31, // 34: rpc.WalletService.ResetSecurityCard:output_type -> google.protobuf.Empty
	6,  // 35: rpc.WalletService.SignMessageSecurityCard:output_type -> rpc.SignMessageSecurityCardResponse
	4,  // 36: rpc.WalletService.SetupSecurityCardV2:output_type -> rpc.SetupSecurityCardResponse
	31, // 37: rpc.WalletService.SignMessageSecurityCardV2:output_type -> google.protobuf.Empty
	7,  // 38: rpc.WalletService.StartDiagnosticSession:output_type -> rpc.DiagnosticSessionDescriptor
	8,  // 39: rpc.WalletService.PerformDiagnosticScanForUtxos:output_type -> rpc.ScanProgressUpdate
	11, // 40: rpc.WalletService.SubmitDiagnosticLog:output_type -> rpc.DiagnosticSubmitStatus
	13, // 41: rpc.WalletService.PrepareSweepTx:output_type -> rpc.PrepareSweepTxResponse
	15, // 42: rpc.WalletService.SignAndBroadcastSweepTx:output_type -> rpc.SignAndBroadcastSweepTxResponse
	17, // 43: rpc.WalletService.StartChallengeSetup:output_type -> rpc.SetupChallengeResponse
	31, // 44: rpc.WalletService.FinishRecoveryCodeSetup:output_type -> google.protobuf.Empty
	31, // 45: rpc.WalletService.PopulateEncryptedMuunKey:output_type -> google.protobuf.Empty
	31, // 46: rpc.WalletService.Save:output_type -> google.protobuf.Empty
	24, // 47: rpc.WalletService.Get:output_type -> rpc.GetResponse
	31, // 48: rpc.WalletService.Delete:output_type -> google.protobuf.Empty
	31, // 49: rpc.WalletService.SaveBatch:output_type -> google.protobuf.Empty
	28, // 50: rpc.WalletService.GetBatch:output_type -> rpc.GetBatchResponse
	28, // 51: rpc.WalletService.GetByPrefix:output_type -> rpc.GetBatchResponse
	33, // [33:52] is the sub-list for method output_type
	14, // [14:33] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_wallet_service_proto_init() }
func file_wallet_service_proto_init() {
	if File_wallet_service_proto != nil {
		return
	}
	file_wallet_service_proto_msgTypes[6].OneofWrappers = []any{
		(*scanProgressUpdate_FoundUtxoReport)(nil),
		(*scanProgressUpdate_ScanComplete)(nil),
	}
	file_wallet_service_proto_msgTypes[15].OneofWrappers = []any{}
	file_wallet_service_proto_msgTypes[19].OneofWrappers = []any{
		(*value_NullValue)(nil),
		(*value_DoubleValue)(nil),
		(*value_IntValue)(nil),
		(*value_LongValue)(nil),
		(*value_StringValue)(nil),
		(*value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_service_proto_rawDesc), len(file_wallet_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_service_proto_goTypes,
		DependencyIndexes: file_wallet_service_proto_depIdxs,
		EnumInfos:         file_wallet_service_proto_enumTypes,
		MessageInfos:      file_wallet_service_proto_msgTypes,
	}.Build()
	File_wallet_service_proto = out.File
	file_wallet_service_proto_goTypes = nil
	file_wallet_service_proto_depIdxs = nil
}
