package io.muun.apollo.domain.model

enum class SecurityLevel {
    ANON,               // NO (EMAIL + PASSWORD), NO RC, NO EMERGENCY KIT
    EMAIL,              // NO RC, NO EMERGENCY KIT
    EMAIL_AND_RC,       // NO EMERGENCY KIT
    DONE,               // EVERYTHING SET UP! (FULLY NON-CUSTODIAL)
    SKIPPED_EMAIL_ANON, // SKIPPED EMAIL, NO RC, NO EMERGENCY KIT
    SKIPPED_EMAIL_RC,   // SKIPPED EMAIL, NO EMERGENCY KIT
    SKIPPED_EMAIL_DONE; // SKIPPED EMAIL, EVERYTHING ELSE SET UP! (FULLY NON-CUSTODIAL)
}
