name: pr
on: pull_request

# Note: we'll reference actions by commits for 'reproducibility sakes' (we don't
# want an action author to change the tag reference and break our reproducibility).

jobs:
  pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # Matches tag v4.0.0
        # https://github.com/docker/setup-buildx-action/releases/tag/v4.0.0

        with:
          buildkitd-flags: --debug

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # Matches tag v6.0.2
        # https://github.com/actions/checkout/releases/tag/v6.0.2

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # Matches tag v6.1.0
        # https://github.com/gradle/actions/releases/tag/v6.1.0

      - name: Create output dir
        run: |
          mkdir -p apk

      - name: Build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # Matches tag v7.1.0
        # https://github.com/docker/build-push-action/releases/tag/v7.1.0

        with:
          file: android/Dockerfile
          context: .
          outputs: apk

      - name: Upload APK
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # Matches tag v7.0.1
        # https://github.com/actions/upload-artifact/releases/tag/v7.0.1

        with:
          name: apk
          path: apk/apolloui-prod-*-release-unsigned.apk
